import { useMemo, useState } from 'react';
import { CalendarDays, ChevronRight, Clock3, MapPin, Search, ShieldCheck, Ticket, Users, BarChart3, Plus, Menu, X, ArrowUpRight } from 'lucide-react';

type Event = { id:number; title:string; category:string; date:string; time:string; location:string; price:string; attendees:number; image:string; featured?:boolean };
const events:Event[]=[
{id:1,title:'Future of Digital Business Summit',category:'Business',date:'24 Sep 2026',time:'10:00 AM',location:'Mumbai, Maharashtra',price:'₹1,499',attendees:842,featured:true,image:'https://images.unsplash.com/photo-1505373877841-8d25f7d46678?auto=format&fit=crop&w=1200&q=80'},
{id:2,title:'Design & Innovation Conference',category:'Technology',date:'03 Oct 2026',time:'9:30 AM',location:'Pune, Maharashtra',price:'₹999',attendees:524,image:'https://images.unsplash.com/photo-1540575467063-178a50c2df87?auto=format&fit=crop&w=1200&q=80'},
{id:3,title:'Music & Culture Night',category:'Entertainment',date:'17 Oct 2026',time:'7:00 PM',location:'Nashik, Maharashtra',price:'₹699',attendees:1160,image:'https://images.unsplash.com/photo-1506157786151-b8491531f063?auto=format&fit=crop&w=1200&q=80'}];
const stats=[['12.8K','Total Registrations','+18.4%'],['184','Live Events','+12.1%'],['₹24.6L','Revenue Generated','+21.7%'],['96.2%','Satisfaction Rate','+4.8%']];
export function App(){const[query,setQuery]=useState('');const[category,setCategory]=useState('All');const[menu,setMenu]=useState(false);const categories=['All','Business','Technology','Entertainment'];const filtered=useMemo(()=>events.filter(e=>(category==='All'||e.category===category)&&`${e.title} ${e.location}`.toLowerCase().includes(query.toLowerCase())),[query,category]);return <div className="app">
<header className="nav"><div className="brand"><span className="brand-mark">E</span> EVENTORA</div><button className="mobile-menu" onClick={()=>setMenu(!menu)}>{menu?<X/>:<Menu/>}</button><nav className={menu?'nav-links open':'nav-links'}><a href="#events">Explore Events</a><a href="#dashboard">Dashboard</a><a href="#about">About</a><button className="ghost">Sign in</button><button className="primary small">Create account</button></nav></header>
<main><section className="hero"><div className="hero-copy"><div className="eyebrow"><span className="pulse"></span> THE SMARTER WAY TO MANAGE EVENTS</div><h1>Plan. Connect.<br/><span>Experience.</span></h1><p>One powerful platform for discovering events, managing registrations, engaging attendees, and growing your event business.</p><div className="hero-actions"><button className="primary">Explore events <ArrowUpRight size={18}/></button><button className="secondary">Become an organizer</button></div><div className="trust"><ShieldCheck size={17}/> Secure & reliable <span>•</span> <Users size={17}/> 50K+ attendees</div></div><div className="hero-card"><img src={events[0].image}/><div className="hero-card-overlay"><span className="tag">FEATURED EVENT</span><h3>Future of Digital Business Summit</h3><div className="meta"><CalendarDays size={15}/> 24 Sep 2026 <MapPin size={15}/> Mumbai</div></div></div></section>
<section className="stats" id="dashboard">{stats.map(([n,l,p])=><div className="stat" key={l}><b>{n}</b><span>{l}</span><em>{p}</em></div>)}</section>
<section className="section" id="events"><div className="section-head"><div><div className="kicker">DISCOVER</div><h2>Events worth attending</h2><p>Find your next experience from curated events.</p></div><button className="outline">View all <ChevronRight size={17}/></button></div><div className="filters"><div className="search"><Search size={18}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search events or locations..."/></div>{categories.map(c=><button key={c} className={category===c?'filter active':'filter'} onClick={()=>setCategory(c)}>{c}</button>)}</div><div className="event-grid">{filtered.map(e=><article className="event" key={e.id}><div className="event-image"><img src={e.image}/><span>{e.category}</span></div><div className="event-body"><h3>{e.title}</h3><div className="event-meta"><CalendarDays size={15}/>{e.date}<Clock3 size={15}/>{e.time}</div><div className="event-meta"><MapPin size={15}/>{e.location}</div><div className="event-bottom"><strong>{e.price}</strong><small><Users size={14}/> {e.attendees} joined</small><button className="icon-btn"><ArrowUpRight size={17}/></button></div></div></article>)}</div></section>
<section className="organizer" id="about"><div><div className="kicker">FOR ORGANIZERS</div><h2>Everything you need to run better events.</h2><p>Create, manage, promote and measure your events from one professional workspace.</p><button className="primary">Open organizer dashboard <ArrowUpRight size={18}/></button></div><div className="feature-grid"><div><BarChart3/><b>Real-time analytics</b><span>Track registrations, revenue and engagement.</span></div><div><Ticket/><b>Smart ticketing</b><span>Flexible ticket types and capacity controls.</span></div><div><Users/><b>Attendee management</b><span>Manage participants and event communication.</span></div><div><Plus/><b>Fast event creation</b><span>Build polished event pages in minutes.</span></div></div></section></main>
<footer><div className="brand"><span className="brand-mark">E</span> EVENTORA</div><span>© 2026 EVENTORA. Professional event management platform.</span></footer></div>}